# Book settings
title: ASTraL
author: Deepak Cherian
logo: logo.png
only_build_toc_files: true

repository:
  url                       : https://github.com/dcherian/astral  # The URL to your book's repository
  path_to_book              : "notebooks/"  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links

html:
  use_repository_button: true
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: 'off'
